### ISSUE TITLE
The language is set to schinese, which is actually tchinese.

### ISSUE THREAD

**Issue by 670233975** [SteamAutoCracks/Steam-auto-crack#1]
Is the language table misplaced?

Thank you for the program. It's very convenient.

**Comment by oureveryday** [comment]
> Is the language table misplaced?
> 
> Thank you for the program. It's very convenient.

If you input "schinese" when config, "schinese" will be written to language.txt. Use "9.Open EMU setting floder" for open config folder and check language.txt. It must be the game doesn't support schinese.
