### ISSUE TITLE
closes/crashes automatically

### ISSUE THREAD

**Issue by achyutde13** [SteamAutoCracks/Steam-auto-crack#14]
Hi, anytime I try to crack any clean steam files game with this is always crashes at the same exact step, I have attached an image, as soon as I press Y it just closes, I can see some other text appear in the next line but it closes too fast for me to read it, I can still find the temp files in the temp folder but my game files stay the same and nothing gets modified in the game folder
![Capture](https://user-images.githubusercontent.com/38592400/178518997-017430c6-fbe5-4d63-bddc-57deed77613c.PNG)
.

**Comment by oureveryday** [comment]
Download https://github.com/oureveryday/Steam-auto-crack/archive/refs/heads/master.zip and run src/SteamAutoCrack.cmd then try again.

**Comment by achyutde13** [comment]
Yeah that worked, it didn't close at the step anymore and completed the process. Thanks!
