### ISSUE TITLE
Program doesn't fit my screen resolution lmao [1366x768]

### ISSUE THREAD

**Issue by cRu572Vltn** [SteamAutoCracks/Steam-auto-crack#15]
It's not a big bother as I'm still using an old version of the program, without the new UI, but I'm pointing out this inconvenience just in case.
The same happens when clicking on the different buttons
![screen-opt](https://user-images.githubusercontent.com/82488025/180850229-3532845b-6140-49cd-9c44-8e191e5b82cf.jpg)
.

**Comment by oureveryday** [comment]
Can you check your DPI Scaling level in Display Settings?
This window sized 800x600: `Gui Show,w600 h800,Steam Auto Crack %Ver%`
So it should runs no problem for 1366x768 screen.

**Comment by cRu572Vltn** [comment]
> Can you check your DPI Scaling level in Display Settings? This window sized 800x600: `Gui Show,w600 h800,Steam Auto Crack %Ver%` So it should runs no problem for 1366x768 screen.

The DPI is fine, it seems normal Ig? I've never changed any settings on the screen anyway. I don't have anything to do with re-scaling either.
![share](https://user-images.githubusercontent.com/82488025/180904461-2c6e1518-6166-451d-b488-5a66c09a8252.jpg)

I've sent the program to a friend and she seems to have the same problem (Her monitor is 1024x768, tried it on 800x600 as well). Trying on lower resolutions seems to make the problem worse.

**Comment by oureveryday** [comment]
This program is done on a high DPI settings, so there will be problem for smaller monitors.
Hard to fix it since the window size and components is fixed, if enable resize function menu can't be fully displayed...
You can try this tool to move the window: https://stefansundin.github.io/altdrag/

**Comment by cRu572Vltn** [comment]
I had no idea that such tool existed. It looks very useful, thank you.

**Comment by oureveryday** [comment]
Should be fixed in version 2.2.0.

**Comment by oureveryday** [comment]
3.0 Version should works fine on all screens.
