### ISSUE TITLE
hellow homesome boy  tell  me some  questions

### ISSUE THREAD

**Issue by SuShuo125** [SteamAutoCracks/Steam-auto-crack#17]
能不能解答下我几个疑问
1.这个软件的功能是什么。是直接添加我没有的游戏吗，还是说必须先下载好游戏，然后进行破解，让它直接在没有steam的环境下直接启动
2.这个game path 是填要下载好的游戏存放路径吗

**Comment by SuShuo125** [comment]
我刚才试了下hellow kindow 成功了，就是说这款软件是脱壳用的吧，不能直接增加没有的游戏。
这个软件能够对D加密游戏适用吗
这个软件破解的游戏不能联网吧

**Comment by oureveryday** [comment]
1. 必须先下载好游戏，然后进行破解，让它直接在没有steam的环境下直接启动。
2. 是填要下载好的游戏存放路径。
3. 可以自动脱SteamStub壳+应用Goldberg模拟器，D加密不能用，部分游戏可以联机
