### ISSUE TITLE
The program only accept the 'N'

### ISSUE THREAD

**Issue by GabrYLive** [SteamAutoCracks/Steam-auto-crack#2]
The program will always only accept the character 'N' but not the 'Y'
I already tried with on-screen keyboard or changing the keyboard layout.

**Comment by joroyt** [comment]
How do I fix it? I have the same problem.

**Comment by GabrYLive** [comment]
> How do I fix it? I have the same problem.

I found out wheres the problem; its used a "build-in" windows function where instead of accepting the N or the Y, is based on your windows language.
In my case in Italian the "yes" its "si" so I had to press the S key instead of the Y.

**Comment by joroyt** [comment]
Thanks, it worked!

**Comment by oureveryday** [comment]
Problem should be fixed now.
