### ISSUE TITLE
Cracking "祈風 Inorikaze(App ID:992740)" fails.

### ISSUE THREAD

**Issue by Yuubagi** [SteamAutoCracks/Steam-auto-crack#23]
I have tried this and it succeeds in cracking in almost all games, but fails to crack only in "Inorikaze".
After running auto crack, the log shows "Crack Success" in the log, but actually it cannot be activated.

**Comment by oureveryday** [comment]
This game is built on a older version steam_api.dll so Goldberg EMU dll won't works (Or a part of Custom DRM?).
Please upload game file here and I will make a crack with steamclient_loader.
https://cs.rin.ru/forum/viewtopic.php?f=10&t=126752
