### ISSUE TITLE
Achievement API page gives error 404

### ISSUE THREAD

**Issue by Ew4n1011** [SteamAutoCracks/Steam-auto-crack#27]
Attempting to crack hades, it gave an error on generating achievments and said to go to this site: https://api.xan105.com/steam/ach/1145360

However whenever I go there (tried on Firefox and Microsoft Edge), it gives a warning, which I then allow but after allowing it show error 404

**Comment by Ew4n1011** [comment]
I have no idea if this has something to do with it too, but I noticed it was made by the same person as Achievement Watcher. And now that repo is archived, so maybe something to do with that?

**Comment by oureveryday** [comment]
The only way is to use steam official API now with a Steam web API key since xan105 is away. (She will be back soon)

**Comment by oureveryday** [comment]
Version 3.0 works fine with Steam Web API Key.
