### ISSUE TITLE
Possibility without internet connection

### ISSUE THREAD

**Issue by ghost** [SteamAutoCracks/Steam-auto-crack#28]
Is there a way to use the tool without an internet connection? With version 2.3.2 I was able to create and use my Steam game without an internet connection.

Only version 3.0.1 always needs an internet connection. You can also do this without an internet connection. I would also like to donate something for the great work

Thanks for the tool helps a lot for beginners.

**Comment by oureveryday** [comment]
The offline generation function already exists. Select on `Generate Game Info` -> `Generator API` -> `Offline`
Also added donation address in Readme.md.
I'd appreciate it if you could donate this project.

**Comment by ghost** [comment]
> The offline generation function already exists. Select on `Generate Game Info` -> `Generator API` -> `Offline` Also added donation address in Readme.md. I'd appreciate it if you could donate this project.

there comes the error when I do it offline here is a picture

NEW
https://bilderupload.org/bild/5a9918888-18d6dc35e506fc23347221888

**Comment by oureveryday** [comment]
It should be fixed in the latest 3.0.2 version.
