### ISSUE TITLE
Can't run for some reason

### ISSUE THREAD

**Issue by TrevorDeyo** [SteamAutoCracks/Steam-auto-crack#29]
Can't run for some reason. It doesn't say anything or do anything. Running as admin doesn't help and turning off anti-virus didn't help either. The 2.3.2 release works fine but any of the 3.X don't work for me.

**Comment by Yarpopcat08** [comment]
Try installing .NET framework. Hope I could help somehow. I think I installed .NET 6 (or older), and it worked.
Updated: Here's the link to the Framework I installed: https://download.visualstudio.microsoft.com/download/pr/d37ab8e6-095b-4f42-bea5-f519b3c62b68/3b87e1c571a3fc49607acc821d3f107a/windowsdesktop-runtime-6.0.13-win-x86.exe

**Comment by TrevorDeyo** [comment]
Whats werid is for my friend when he started it. It actually told him he needed to download .net and for me it wasn't doing that so I assumed it it was something else and I already had .net 6.0.4 but I downloaded the link you shared and it fixed it for me thank you.

**Comment by Yarpopcat08** [comment]
You're welcome!
