### ISSUE TITLE
ERROR LAUNCH GAME

### ISSUE THREAD

**Issue by PeppoDevStudio** [SteamAutoCracks/Steam-auto-crack#31]
Hi, i have this error
![image](https://user-images.githubusercontent.com/70705179/218321009-a8da5832-fec9-4b34-a36b-a4c4fce60516.png)

**Comment by oureveryday** [comment]
This is an Goldberg Steam Emulator problem, report it in https://cs.rin.ru/forum/viewtopic.php?f=29&t=91627
