### ISSUE TITLE
Handsome boy has a few questions he'd like to ask

### ISSUE THREAD

**Issue by SuShuo125** [SteamAutoCracks/Steam-auto-crack#33]
First of all, I would like to express my respect to you. This is the most comfortable software I have ever used, it is very powerful and only. If you have Chinese payment method, I would like to invite you to have a cup of coffee.
1. Does Golbgerd generate achievements? Does it work with achievement observers? I found out from steamlunch that it requires a web api, which costs $5 to apply for.
 2. This application is not effective for D encryption. Is there any way I can play the game that D encryption has not been cracked yet, in terms of your knowledge channel? I found steamlite and steamclient_loader, and they seem to be able to work. I'm not sure about the specific principle, but I didn't understand it because of the language
3. Under what circumstances can I play multiplayer games? Can I play online patches as long as it is a LAN game? Which emulators can do that
     Finally, I sincerely express my respect to you. If you have the Chinese way of payment, I would like to invite you to have a cup of coffee. I hope you will always be handsome

**Comment by oureveryday** [comment]
1. Yeah it generates achievements for it. There is a steam web API key `1DD0450A99F573693CD031EBB160907D`
2. You need application ticket from a geniue game onwer, you can try Greenluma with family share etc.
3. You can find online fix from https://online-fix.me/

I couldn't add Chinese payment method right now for some reasons. 
Also i will add Chinese language in SteamAutoCrack in the future.
（其实没必要在这说英文）
