### ISSUE TITLE
When i crack the game Half-Life with steam_id 70 i get this

### ISSUE THREAD

**Issue by h1laryz** [SteamAutoCracks/Steam-auto-crack#39]
---------------------------
Fatal Error
---------------------------
Failed to initalize authentication interface. Exiting...

---------------------------
OK   
---------------------------

Also, if I launch steam it asks to buy the game

**Comment by h1laryz** [comment]
![image](https://github.com/oureveryday/Steam-auto-crack/assets/71406854/40721969-9698-40b5-b63b-45668ea31679)

**Comment by h1laryz** [comment]
![image](https://github.com/oureveryday/Steam-auto-crack/assets/71406854/8feafe8e-769b-44f4-b248-50323aa69459)
logs

**Comment by oureveryday** [comment]
This problem is because of game's custom DRM, please find a crack on cs.rin.ru/forum
