### ISSUE TITLE
Config is not used

### ISSUE THREAD

**Issue by prdp19** [SteamAutoCracks/Steam-auto-crack#45]
I have the problem that it doesn't matter what I use under

`TEMP\steam_settings`

and/or

`Goldberg\steam_settings`

**none** of it is applied. 

Neither the language (english), nor the name, nor anything else (of course I have removed the EXAMPLE from the .txt and the steam_settings folder). The window always looks like this for me:

![screen](https://github.com/oureveryday/Steam-auto-crack/assets/68145407/3500fe12-605d-4456-998f-25bf83e63766)

Why is that?

I would also like to set Generator API to Offline permanently.

Then I have the question, what is the difference between using force or not?
Isn't it better to always use force (e.g. for the language)?

**Comment by oureveryday** [comment]
The emulator is applied into game folder, you don't need to manually copy it from temp file.

To save config file, go `settings` and enable `Save config file`.

Always use `force` as it if it's off it will read config from the user's Appdata folder.

**Comment by prdp19** [comment]
> The emulator is applied into game folder, you don't need to manually copy it from temp file.
> 
> To save config file, go `settings` and enable `Save config file`.

That's what I was looking for - thank you. Works perfectly.
Very cool tool, thanks for your work!!!

**Is it possible (if successful) to delete the .bak files directly?
Could you add this option, if it does not already exist (if it exists: where?).**

> 
> Always use `force` as it if it's off it will read config from the user's Appdata folder.

Ah, ok!

May I ask you a few more optional questions?
a.) SteamStub = Steamless, correct?
b.) What is the "Keep .bind-Section", "Realign Sections", "Keep DOS Stub Data" for and what effects do they have?

**Comment by oureveryday** [comment]
`Is it possible (if successful) to delete the .bak files directly?`

The backup of original file is for recover the crack (Codex/Rune also doing so, backuped a original file), no plan of adding that.

`May I ask you a few more optional questions?`

Keep them default if you don't understand, as these are Steamless unpacker settings.
