### ISSUE TITLE
Chants of Sennaar won't open after cracked

### ISSUE THREAD

**Issue by Kelvets** [SteamAutoCracks/Steam-auto-crack#47]
![Screenshot_259](https://github.com/oureveryday/Steam-auto-crack/assets/3800465/1760c0cf-c9cd-461f-8588-55bb379943c2)

Chants of Sennaar is supposed to only have Steam DRM. I cracked the game with the settings above and after running the .exe, I just get a black screen forever. Without the cracking the game runs fine.

To be fair, I have been unable to crack the last few games on Steam with the previous tool I was using either, which made me pursue and find this one, thinking the other one was broken. Could it be that Steam recently updated its anti-cracking measures?

**Comment by oureveryday** [comment]
Maybe they are using newer version steam API which needs a updated emulator. Will update it later.

**Comment by oureveryday** [comment]
Can you tell me the exact game name?

**Comment by Kelvets** [comment]
The exact name is "Chants of Sennaar", like I wrote in the title. The SteamID is in the picture posted.

**Comment by oureveryday** [comment]
Will check it later.

**Comment by txyyh** [comment]
Howerver, Chants of Sennaar works well on my device.

BuildID 12333519

**Comment by oureveryday** [comment]
So this is not this software's problem.
You might need to install some runtime libraries.

**Comment by Kelvets** [comment]
I installed NET 6.0 both x86 and x64, re-downloaded the crack tool from scratch, and ran it as administrator. I bought a random game SUMMERHOUSE to test the tool but it still doesn't work. When I run the executable from the game's folder afterwards, it still counts my playtime within Steam and the "Play" button becomes "Stop", indicating the game is being recognized normally and that it's not the cracked version that I'm playing.

What other runtime libraries would I need besides NET?

Do you see any error in the log output below that could give a clue as to what's wrong? Notice the messages highlighted in yellow.

![Screenshot_328](https://github.com/oureveryday/Steam-auto-crack/assets/3800465/5d59b366-b7ce-422a-921f-c5e35f9df97c)
![Screenshot_329](https://github.com/oureveryday/Steam-auto-crack/assets/3800465/1faf556b-e544-436d-8e48-5b78454b54c5)
![Screenshot_330](https://github.com/oureveryday/Steam-auto-crack/assets/3800465/a84cb482-dcdb-40b7-af01-404f847ec6e9)

**Comment by txyyh** [comment]
My SUMMERHOUSE(Build 13691441) also works well.
Maybe you can check if you game's steam_api64.dll has been actually changed after crack.
