### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by DJ-HeYong** [SteamAutoCracks/Steam-auto-crack#48]
![屏幕截图 2023-12-29 113545](https://github.com/oureveryday/Steam-auto-crack/assets/89385267/6b344f89-5838-43a1-8937-9674b23a7391)

Here are some warning and error logs

**Comment by oureveryday** [comment]
It seems u are in China, which cannot get stable connection to steam.
Please retry or use a VPN.

**Comment by DJ-HeYong** [comment]
I'm in China, thanks, I'll try using a vpn





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "oureveryday/Steam-auto-crack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月31日(星期天) 晚上11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [oureveryday/Steam-auto-crack] Hi！ (Issue #48)





 
It seems u are in China, which cannot get stable connection to steam.
 Please retry or use a VPN.
