### ISSUE TITLE
Crack Only feature not working properly

### ISSUE THREAD

**Issue by radwaste** [SteamAutoCracks/Steam-auto-crack#49]
The Crack Only feature does not generate the crack but simply copies the .exe and .exe.bak as the same (uncracked) file into the Crack Only folder.
![Screenshot 2024-03-15 225849](https://github.com/oureveryday/Steam-auto-crack/assets/101988080/a7b1cc4f-84db-4796-bf77-646494bb3e34)

**Comment by oureveryday** [comment]
The size should be same as `keep bind section` is enabled by default.
