### ISSUE TITLE
Invalid memory access

### ISSUE THREAD

**Issue by h4zmat** [SteamAutoCracks/Steam-auto-crack#5]
![image](https://user-images.githubusercontent.com/52090956/148702875-73443141-7c6e-4d3d-8fe0-b22135726170.png)

I get this error after the command prompt pops up. It's allowed through windows firewall.

**Comment by pizzadox11** [comment]
off topic, i must say good job and very immersive work, i liked the part where you can change your own steam id
would be great if this patch would work on dedicated servers too like revemu does

**Comment by oureveryday** [comment]
> ![image](https://user-images.githubusercontent.com/52090956/148702875-73443141-7c6e-4d3d-8fe0-b22135726170.png)
> 
> I get this error after the command prompt pops up. It's allowed through windows firewall.

In which crack part you get this error?

**Comment by h4zmat** [comment]
![image](https://user-images.githubusercontent.com/52090956/151401106-20de210c-3a54-4904-b5dc-68ef6d2992eb.png)
Right after running it. The command prompt opens up, and before any text shows the error pops.

**Comment by oureveryday** [comment]
Please [Download code](https://github.com/oureveryday/Steam-auto-crack/archive/refs/heads/master.zip) then run src/SteamAutoCrack.cmd

**Comment by h4zmat** [comment]
It works fine when I run it that way, thanks.
