### ISSUE TITLE
Can't download/update goldberg emu, here is the log file and a picture of the log

### ISSUE THREAD

**Issue by RubynRuby** [SteamAutoCracks/Steam-auto-crack#51]
![image](https://github.com/oureveryday/Steam-auto-crack/assets/158524595/4b81eeb2-7aca-49ed-ac7c-a45e491b5f4c)
[error.log](https://github.com/oureveryday/Steam-auto-crack/files/15137645/error.log)

**Comment by RubynRuby** [comment]
tried without admin and another time with run as admin, both gave same error

**Comment by RubynRuby** [comment]
a fresh zip extraction -> settings button -> visual glitch of goldberg version

![image](https://github.com/oureveryday/Steam-auto-crack/assets/158524595/4dbb21f8-5f70-4789-80ba-d6e9d7930a27)


after clicking update/download button ->

![image](https://github.com/oureveryday/Steam-auto-crack/assets/158524595/031bb951-cb77-4f1b-8774-e72752007ca1)

and the contents of goldberg folder is deleted

![image](https://github.com/oureveryday/Steam-auto-crack/assets/158524595/46cc8aef-c190-465d-b4af-75ee3f84a3ea)

**Comment by Adephx** [comment]
I have the same issue.

**Comment by oureveryday** [comment]
Will fix it in the future. Currently don't have time.

**Comment by oureveryday** [comment]
This is fixed in version 3.4.0.0.
