### ISSUE TITLE
Support Multiple Language Achievement

### ISSUE THREAD

**Issue by sprinox** [SteamAutoCracks/Steam-auto-crack#52]
it can contain different languages of displayName and description.
See [achievements.json](https://github.com/oureveryday/Steam-auto-crack/files/15323634/achievements.json)
it will be a great help for non english user.

**Comment by oureveryday** [comment]
What script did you used to generate this file? Can I have a look?

**Comment by sprinox** [comment]
i got it from a cracked game which downloaded from Internet

**Comment by sprinox** [comment]
https://partner.steamgames.com/doc/webapi/ISteamUserStats

it seems that ```GetSchemaForGame``` can get the translation by setting the parameter ```l```

**Comment by oureveryday** [comment]
It's too hard to add that as Steam web API only returns one language.

**Comment by sprinox** [comment]
> It's too hard to add that as Steam web API only returns one language.

how about add an option to select the language of achievements.json to download

**Comment by oureveryday** [comment]
考虑一下

**Comment by sprinox** [comment]
https://github.com/Nemirtingas/games-infos

找到个项目有收录游戏信息的，还提供了抓取用的程序。我原来那个json文件应该就是这个生成的

**Comment by oureveryday** [comment]
那个是连接了steamkit3的并且需要个steam账号才可以获取的，免登陆情况下是获取不了的，之前试过这个方案发现不好

**Comment by sprinox** [comment]
https://github.com/Nemirtingas/games-infos/blob/main/steam_retriever/Program.cs

```cs
        async Task GenerateAchievementsFromWebAPI(string appid)
        {
            if (string.IsNullOrEmpty(Options.WebApiKey))
            {
                Program.Instance._logger.Info("  + WebApi key is missing, the tool will not generate achievements list.");
                return;
            }

            try
            {
                int done = 0;
                Program.Instance._logger.Info("  + Trying to retrieve achievements and stats...");

                var response = await LimitSteamWebApiGET(
                    WebHttpClient,
                    new HttpRequestMessage(HttpMethod.Get, $"http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2/?l={Options.Language}&key={Options.WebApiKey}&appid={appid}"));

                if (response.StatusCode == HttpStatusCode.OK)
                {
                    JObject achievements_json = JObject.Parse(await response.Content.ReadAsStringAsync());

                    if (((JObject)achievements_json["game"]).ContainsKey("availableGameStats"))
                    {
                        if (((JObject)achievements_json["game"]["availableGameStats"]).ContainsKey("achievements"))
                        {
                            JArray achievements = (JArray)achievements_json["game"]["availableGameStats"]["achievements"];

                            Directory.CreateDirectory(Path.Combine(Options.OutDirectory, appid));

                            foreach (var achievement in achievements)
                            {
                                achievement["displayName"] = new JObject { { Options.Language, achievement["displayName"] } };
                                achievement["description"] = new JObject { { Options.Language, achievement["description"] } };

                                if (Options.DownloadImages)
                                {
                                    await DownloadAchievementIcon(appid, (string)achievement["name"], new Uri((string)achievement["icon"]));
                                    await DownloadAchievementIcon(appid, (string)achievement["name"] + "_locked", new Uri((string)achievement["icongray"]));
                                }
                            }

                            done |= SaveAchievementsToFile(appid, achievements) ? 1 : 0;
                            if ((done & 1) != 1)
                            {
                                Program.Instance._logger.Info("  + Failed to save achievements.");
                            }
                        }
                        if (((JObject)achievements_json["game"]["availableGameStats"]).ContainsKey("stats"))
                        {
                            Directory.CreateDirectory(Path.Combine(Options.OutDirectory, appid));

                            done |= SaveStatsToFile(appid, achievements_json["game"]["availableGameStats"]["stats"]) ? 2 : 0;
                            if ((done & 2) != 2)
                            {
                                Program.Instance._logger.Info("  + Failed to save stats.");
                            }
                        }
                    }
                }//using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                if (done == 0)
                {
                    Program.Instance._logger.Info("  + No achievements or stats available for this AppID.");
                }
                else
                {
                    Program.Instance._logger.Info("  + Achievements and stats were successfully generated!");
                }
            }
            catch (Exception e)
            {
                Program.Instance._logger.Error($"  + Failed (no achievements or stats?): {e.Message}");
            }
        }
```

可以参考他程序中这段代码加个循环把 Options.Language 在支持的语言里循环一遍，抓取全部语言的信息，感觉就可以实现这个 issue。

**Comment by oureveryday** [comment]
哪个项目的我看看



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/14/2024 22:54 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [oureveryday/Steam-auto-crack] Support Multiple Language Achievement (Issue #52) |

async Task GenerateAchievementsFromWebAPI(stringappid){if(string.IsNullOrEmpty(Options.WebApiKey)){
                Program.Instance._logger.Info("  + WebApi key is missing, the tool will not generate achievements list.");return;}try{intdone=0;
                Program.Instance._logger.Info("  + Trying to retrieve achievements and stats...");varresponse=await LimitSteamWebApiGET(
                    WebHttpClient,new HttpRequestMessage(HttpMethod.Get,$"http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2/?l={Options.Language}&key={Options.WebApiKey}&appid={appid}"));if(response.StatusCode == HttpStatusCode.OK){JObjectachievements_json= JObject.Parse(await response.Content.ReadAsStringAsync());if(((JObject)achievements_json["game"]).ContainsKey("availableGameStats")){if(((JObject)achievements_json["game"]["availableGameStats"]).ContainsKey("achievements")){JArrayachievements=(JArray)achievements_json["game"]["availableGameStats"]["achievements"];

                            Directory.CreateDirectory(Path.Combine(Options.OutDirectory, appid));foreach(var achievement in achievements){
                                achievement["displayName"]=new JObject {{ Options.Language, achievement["displayName"]}};
                                achievement["description"]=new JObject {{ Options.Language, achievement["description"]}};if(Options.DownloadImages){await DownloadAchievementIcon(appid,(string)achievement["name"],new Uri((string)achievement["icon"]));await DownloadAchievementIcon(appid,(string)achievement["name"]+"_locked",new Uri((string)achievement["icongray"]));}}done |= SaveAchievementsToFile(appid, achievements)?1:0;if((done&1)!=1){
                                Program.Instance._logger.Info("  + Failed to save achievements.");}}if(((JObject)achievements_json["game"]["availableGameStats"]).ContainsKey("stats")){
                            Directory.CreateDirectory(Path.Combine(Options.OutDirectory, appid));done |= SaveStatsToFile(appid, achievements_json["game"]["availableGameStats"]["stats"])?2:0;if((done&2)!=2){
                                Program.Instance._logger.Info("  + Failed to save stats.");}}}}//using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())if(done==0){
                    Program.Instance._logger.Info("  + No achievements or stats available for this AppID.");}else{
                    Program.Instance._logger.Info("  + Achievements and stats were successfully generated!");}}catch(Exceptione){
                Program.Instance._logger.Error($"  + Failed (no achievements or stats?): {e.Message}");}}

可以参考他程序中这段代码加个循环把 Options.Language 在支持的语言里循环一遍，抓取全部语言的信息，感觉就可以实现这个 issue。

**Comment by sprinox** [comment]
https://github.com/Nemirtingas/games-infos/blob/main/steam_retriever/Program.cs

就上面那个

**Comment by oureveryday** [comment]
到时候看看

**Comment by oureveryday** [comment]
这个还真的不好实现，因为我的软件里面 GetSchemaForGame 是异步执行的，也就是说先获取了Schema在根据生成的东西生成achievement.json

后面的成就和统计信息生成都是靠获取的这个schema

而且调用Steam的API是有限制的，之所以那个文件可以有多个语言是因为他用了Steam3进行生成，但那需要一个拥有这个游戏的人的SteamID并且要再Steam3里面登陆Steam账号（不能匿名登陆）

**Comment by sprinox** [comment]
可以在生成 achievement.json 的函数也 GetSchemaForGame
在这里面多调用几次获取不同语言的

或者麻烦的话，直接第一次 GetSchemaForGame 的时候把当前软件语言当作参数获取当前语言的 achievement.json

**Comment by oureveryday** [comment]
那也可以

**Comment by oureveryday** [comment]
版本3.4.1.1已添加

**Comment by maicol07** [comment]
Hi @oureveryday,
language should be selected from the Goldberg steam emu language, not the app one. Can you change it?
Thanks

**Comment by oureveryday** [comment]
https://github.com/SteamAutoCracks/Steam-auto-crack/commit/1c3c278ae17280be9b98d00ac68efeb07d73fced

Did a hotfix

**Comment by maicol07** [comment]
> https://github.com/SteamAutoCracks/Steam-auto-crack/commit/1c3c278ae17280be9b98d00ac68efeb07d73fced
> 
> Did a hotfix

Thanks. Is there an ETA for the next release?

**Comment by oureveryday** [comment]
It's hotfix, download again in releases
