### ISSUE TITLE
Finger

### ISSUE THREAD

**Issue by heavyutils** [SteamAutoCracks/Steam-auto-crack#54]
Does this remove the rumored fingerprinting in steam_api.dll? If not, and it's indeed real, I guess it should?

**Comment by oureveryday** [comment]
What did you mean? This program will automatically replace the steam_api.dll to the Goldberg steam emulator one.

**Comment by heavyutils** [comment]
Oh ok 👍 i guess that solves it

I just meant if there were any traces of my steam account. But if it just replaces the whole file altogether with a completely unrelated one, then it's solved
