### ISSUE TITLE
Back 4 blood

### ISSUE THREAD

**Issue by Koriebonx98** [SteamAutoCracks/Steam-auto-crack#56]
Tried the tool, it failed to unpack exe’s and stubs. (Not latest release of crack tool)

game still ran but multiplayer wouldn’t work 
They have recently removed denouvo too, it would be nice to play this game offline lan

**Comment by oureveryday** [comment]
Some multiplayer game needs server side ticket verification. So in this case the Goldberg emulator won't work.
Also if the game is able to run directly, there is no SteamStub.
