### ISSUE TITLE
the game didnt crack

### ISSUE THREAD

**Issue by pablorere** [SteamAutoCracks/Steam-auto-crack#60]
0xe0000010  error apears

**Comment by oureveryday** [comment]
Please send a screenshot of the error.
Also please tell me the game name.

**Comment by pablorere** [comment]
![image](https://github.com/user-attachments/assets/e9b620e4-b9a8-48bb-b218-71cc0f9ccc64)
the game is city driver

**Comment by oureveryday** [comment]
Please send screenshot and give me steam link of the game.

**Comment by oureveryday** [comment]
That is aderow drm, not crackable by my app. Find crack elsewhere.
