### ISSUE TITLE
Some features request

### ISSUE THREAD

**Issue by Keepinmindy** [SteamAutoCracks/Steam-auto-crack#62]
Hey, I love your tool, really useful and time saving.

Would it be possible to add sounds to achievements ? Like the defaut steam sound or multiples sounds to choose from like PS4, PS5, Xbox ? 

The cherry on the top would be to trigger a screenshot whenever an achievement is unlocked, I use the official Steam overlay on top of the golderg interface so the easiest way would be to just trigger a simple keybind that could be modified whenever an achievement is unlocked.

Thank you so much for your work !

**Comment by oureveryday** [comment]
Please request that feature in goleberg emulator (There ar mamy gbe_fork)
