### ISSUE TITLE
game start Error Steam_Client::GetISteamHTTP()

### ISSUE THREAD

**Issue by Boollan** [SteamAutoCracks/Steam-auto-crack#63]
game log:

INTERFACE=STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001
CALLER FN=Steam_Client::GetISteamHTTP()
APPID=268910
TIME=2024/09/02 - 13:25:36

inoperative

**Comment by Boollan** [comment]
![image](https://github.com/user-attachments/assets/cad064f5-261b-481f-ab1e-3add3d03949d)

**Comment by oureveryday** [comment]
Try enable generate interfaces.

**Comment by Keepinmindy** [comment]
Same issue and enabling "Generate Steam Interface" is not working. 
Do you have any idea ?

**Comment by oureveryday** [comment]
Maybe this is caused by the latest steam sdk version. Try use different version gbe_fork.

**Comment by Keepinmindy** [comment]
It worked with this fork https://github.com/Detanup01/gbe_fork/releases/download/release-2024_09_15/emu-win-release.7z

Thanks for the quick answer oureveryday.
