### ISSUE TITLE
How to close the achievement pop-up window in the upper right corner?

### ISSUE THREAD

**Issue by erlwm** [SteamAutoCracks/Steam-auto-crack#65]
I have to admit that Goldberg's achievement pop-up is a bit rudimentary.
Some games have pop-ups and some don't. The overlay of Shift+Tab doesn't have an on/off option. Do I need to modify the file to turn it on or off?
![Screenshot - 2024-09-18 12 31 52](https://github.com/user-attachments/assets/b71bbe97-794e-4132-9ce8-260b1c151eb9)

**Comment by oureveryday** [comment]
You need to enable the 'Enable Overlay' option to enable the overlay.
Also experimental version goldberg emulator is required to use the overlay.
