### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by longvuu** [SteamAutoCracks/Steam-auto-crack#69]
[ERR] [SteamAutoCrack.Core.Utils.EMUGameInfo] Failed to get game info, skipping generate supported languages...(AppID: 2361680)
[ERR] [SteamAutoCrack.Core.Utils.EMUGameInfo] Failed to get game info, skipping generate depots...(AppID: 2361680)
[ERR] [SteamAutoCrack.Core.Utils.EMUGameInfo] Failed to get game info, skipping generate DLCs...(AppID: 2361680)

**Comment by oureveryday** [comment]
Can you retry it?
Aso send me a scrrenshot.

**Comment by longvuu** [comment]
![image](https://github.com/user-attachments/assets/42197710-98f1-489b-9574-69ca782ad02b)

**Comment by oureveryday** [comment]
Cannot unpack file is normal as file is not packed.
For AccessDenied error you need to use steam web api method.
