### ISSUE TITLE
大哥STEAMCDN 获取TOKEN 失败了

### ISSUE THREAD

**Issue by huddhudd** [SteamAutoCracks/Steam-auto-crack#70]
求救， 求教育。 
 
 
![image](https://github.com/user-attachments/assets/ea0d5d33-31e9-4331-8ba2-c28c290cf57e)

**Comment by oureveryday** [comment]
参照DepotDownloader的实现。
https://[github.com/SteamRE/DepotDownloader](https://github.com/SteamRE/DepotDownloader)
