### ISSUE TITLE
could not get rid of steamworks v153

### ISSUE THREAD

**Issue by aleeeh07** [SteamAutoCracks/Steam-auto-crack#71]
after patch this appears
![AEXw8jv](https://github.com/user-attachments/assets/b5aff84f-73de-4fa4-bd06-28d49475cbbe)

**Comment by oureveryday** [comment]
What game do you try to cracking? It seems a denuvo game.

**Comment by aleeeh07** [comment]
> What game do you try to cracking? It seems a denuvo game.

https://store.steampowered.com/app/1874000/Life_is_Strange_Double_Exposure/

**Comment by oureveryday** [comment]
The game uses denuvo, which the tool not supported.
