### ISSUE TITLE
controller issue

### ISSUE THREAD

**Issue by comeonebro** [SteamAutoCracks/Steam-auto-crack#74]
so i cracked a game called rugby league live 4 using this upadated version of the tool and for some reason the controller readings were super finicky. controller would stop working once i started a match and the controller would stop working if i touched any key on my keyboard. so i used the version just before this one and now the game works flawessly. 

EDIT

same issue with the old one except the controller stops working later

**Comment by oureveryday** [comment]
Run generate game infos in goldberg emu. You have to figure it out by yourself.

https://github.com/Detanup01/gbe_fork
