### ISSUE TITLE
Suggestion: Include option to auto-generate the controller file.

### ISSUE THREAD

**Issue by TomTurbine** [SteamAutoCracks/Steam-auto-crack#77]
Some games actually seem to require a controller folder/file to use controllers since steam isn't providing it for them.

Would be a nice feature to include a check box in section 4.

Never knew you could have enough steam games that your client can begin to slow down loading until I hit that point. Only thing I can think of because I have wiped the computer multiple times and upgraded PCs entirely and it still lags. So THANK YOU. Resorted to this and GOG to make my collection no longer require clients to play.

Also found it funny when I learned that somewhere over 2000 games in a profile, it begins to get too much for many phones to load the profile on their web browsers when you go to see the list.

**Comment by oureveryday** [comment]
It seems requires a vaild Steam account to gather controller infos, which stored on Steam ugc.
Maybe I will look into it in the future.

**Comment by TomTurbine** [comment]
Evidently Goldberg is able to generate them from the controller.vdf files that are supposed to be included with the games.

https://gitlab.com/Mr_Goldberg/goldberg_emulator/-/blob/master/scripts/controller_config_generator/parse_controller_vdf.py?ref_type=heads

Assuming no bugs, you could include that.

**Comment by oureveryday** [comment]
> Evidently Goldberg is able to generate them from the controller.vdf files that are supposed to be included with the games.
> 
> https://gitlab.com/Mr_Goldberg/goldberg_emulator/-/blob/master/scripts/controller_config_generator/parse_controller_vdf.py?ref_type=heads
> 
> Assuming no bugs, you could include that.

It seems to require a Steam account, maybe I will try to implement a method which doesn't requires an account.

**Comment by TomTurbine** [comment]
My apologizes, I thought it just converted the controller.vdf file. Either way, thanks for the app, I MUCH prefer to play my games without requiring a client and not trying to pay a mountain of cash to convert my old collection from Steam to GoG.
