### ISSUE TITLE
couldnt crack rpg maker vx ace

### ISSUE THREAD

**Issue by Jorge9811** [SteamAutoCracks/Steam-auto-crack#78]
i launched the program, set the appid (220700) and the folder path to my steam copy of RPG Maker VX Ace, set Generator API to Offline, hit Start and the process finished then I opened rpg maker and the program booted up.

when I try to open a game's .rvproj2 file it crashes like this tho:

![RPGVXAce_20241212_173320928](https://github.com/user-attachments/assets/43fd1d98-1a40-4a8f-a346-1e615037e3c3)

and when you go to File - New Project rpg maker gets stuck until you close it.

**Comment by oureveryday** [comment]
try update goldberg emulator and generate interface file first

**Comment by Jorge9811** [comment]
> try update goldberg emulator and generate interface file first

is that something i gotta go out of my way to do? cause i dont see a button to generate interfaces

when u say update goldberg emulator you mean to download the last version?

is it https://gitlab.com/Mr_Goldberg/goldberg_emulator/-/jobs/4247811310/artifacts/download or something else?

**Comment by oureveryday** [comment]
it's all in the program itself. update is in setting and interface is in the main window

**Comment by Jorge9811** [comment]
> it's all in the program itself. update is in setting and interface is in the main window

ohh I found them

yeah that worked out the program boots up and works normally

thanks!!
