### ISSUE TITLE
some small issue

### ISSUE THREAD

**Issue by nachotacos69** [SteamAutoCracks/Steam-auto-crack#9]
i launched the .exe then i got error rapidly showing up

Powershell is not installed in the system.
Please use Input Folder Path.
'choice' is not recognized as an internal or external command,
operable program or batch file.

**Comment by oureveryday** [comment]
What OS do you using? It only support Windows 7 or higher.
Also try download [This](https://github.com/oureveryday/Steam-auto-crack/archive/refs/heads/master.zip) and run src/SteamAutoCrack.cmd

**Comment by nachotacos69** [comment]
> What OS do you using? It only support Windows 7 or higher. Also try download [This](https://github.com/oureveryday/Steam-auto-crack/archive/refs/heads/master.zip) and run src/SteamAutoCrack.cmd

Win 10 Home

**Comment by nachotacos69** [comment]
same thing happens when using the .cmd

**Comment by oureveryday** [comment]
Try fix your system using sfc tool.
